Check permissions logic
oss-slu/TPEN-interfaces pull request #12
Opened 2024-09-30 05:17 UTC by Matthew-Clendenning

Fixes #11 

What was changed: Created a file that listed the roles and their specific permissions. Used test cases to verify that each role was configured correctly and had the correct permissions.

Why was it changed: These changes were made because student users can't have the same permissions as a teacher/owner of the project.

How was it changed: I created a Permissions dictionary inside the permissions.mjs file where the keys (e.g. OWNER, LEADER, CONTRIBUTOR) represent roles, and their corresponding values are arrays that hold their permissions. Inside the same file is a function called checkPermissions to check that certain roles have certain permissions. I created a helper function called generatePatterns so any order of actions, scopes and entities are accounted for when testing. Finally, I created a separate file called `__test__.mjs` that holds the test cases for each role.

2024-09-30 23:56 UTC, sarah-fidahussain-SLU requested changes
Overall, very thorough and when I ran the __test__.mjs file, all tests passed. There was one case of commented out code that may need to be addressed.

2024-09-30 23:56 UTC, sarah-fidahussain-SLU commented on components/classroom/groups/__test__.mjs
> +    /*test('LEADER cannot UPDATE a MEMBER', () => {
if this code is not needed, maybe explain why it is commented out or remove it?

2024-10-01 20:11 UTC, MutyaSowmya123 requested changes
The code permissions.mjs file is implemented for the given permissions correctly.
Remove the package-lock.json file, as its not required even with just package.json file `npx jest` will still run the test cases.

And update the package.json file with 
```
{
  "devDependencies":{
    "jest":"^29.7.0"
  },
  "scripts": {
      "test": "jest"
  },
  "jest": {
    "transform": {},
    "testMatch": [
      "**/__test__.mjs"
    ]
  }
}
```
just remove this code from package.json file:

```
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.4",
    "babel-jest": "^29.7.0",
```

2024-10-05 02:20 UTC, sarah-fidahussain-SLU approved these changes

2024-10-06 03:17 UTC, MutyaSowmya123 approved these changes

2024-10-06 03:17 UTC, merged