sprint 2 issue 10 resolved
oss-slu/TPEN-interfaces pull request #13
Opened 2024-09-30 15:46 UTC by camilledaugherty

Fixes #10 

What was changed: Created a classroom groups folder. Inside, defined 3 roles (owner, leader, contributor) as well as constants for actions, scopes, and entities for use within the classroom interface. Additionally, wrote test cases to make sure the constants are correctly defined.

Why it was changed: This change creates a base structure on which to build our classroom functionality on. The roles and permission parameters frameworks provide a jumping-off point to implement these capabilities in future issues.
 
How it was changed: Two JavaScript files were created - one for roles and one for permissions parameters. These files contain constants to be further expanded on. Test cases were written using Jest, and are located in __test__.mjs. Finally, a package.json file was included to ensure tests run correctly.

2024-09-30 22:17 UTC, Matthew-Clendenning requested changes
Possibly make the code look cleaner and reduce redundancy. Try using for loops.

2024-10-01 20:26 UTC, MutyaSowmya123 requested changes
To reduce the code redundancy in the testcases using a function like this

```
const testProperties = (obj, properties) => {
    properties.forEach(prop => {
        expect(obj).toHaveProperty(prop, prop);
    });
};
```

2024-10-06 03:08 UTC, Matthew-Clendenning approved these changes

2024-10-06 03:20 UTC, MutyaSowmya123 approved these changes

2024-10-06 03:20 UTC, merged