Fixes #3
oss-slu/TPEN-interfaces pull request #18
Opened 2024-10-14 04:23 UTC by sarah-fidahussain-SLU

1. **What was changed**: A web component was defined and accepts a project ID as an attribute. When a projectID exists, the component triggers an API call and fetches project data and displays it. When the project ID changes, the component recognizes the change and displays the data to the new project ID.
1. **Why was it changed**: These changes are needed because a web component allows for the reusability of fetching project data.
2. **How was it changed**: 
- web-component.js: defines a custom web component that fetches project data based on a project ID and displays the project's name, creator, and contributors. 
- web-component.html: a usage test, showing how to include the custom component in a webpage, pass a project-id to it, and have it fetch and display data. 
- create-project.js: Uses TPEN api to create a project. This is used later in the web-component.html as we need a project to get a valid project ID to test the web component functionality.

2024-10-14 22:35 UTC, Matthew-Clendenning commented on components/classroom/web-component.html
> +    <script type="module">
Maybe move this script into a js file to make the html file cleaner.

2024-10-14 22:39 UTC, Matthew-Clendenning commented on components/classroom/web-component.js
> +        this.attachShadow({ mode: 'open' });
What does this line of code do?

2024-10-14 22:44 UTC, Matthew-Clendenning requested changes
The code is readable. However, there are some recommendations on how to organize the code and adding some more comments explaining certain parts of the code.

2024-10-17 17:46 UTC, MutyaSowmya123 requested changes

2024-10-17 18:02 UTC, sarah-fidahussain-SLU commented on components/classroom/create-project.js
Is there another way to test the code since we need to create a project to get a valid project ID?

2024-10-18 15:17 UTC, MutyaSowmya123 commented on components/classroom/create-project.js
Are you able to create and fetch with that single line?

2024-10-20 06:41 UTC, MutyaSowmya123 approved these changes

2024-10-21 14:00 UTC, Matthew-Clendenning approved these changes

2024-10-21 22:04 UTC, merged