hasPermission function i
oss-slu/TPEN-interfaces pull request #19
Opened 2024-10-14 19:12 UTC by camilledaugherty

Fixes #16 
What was changed: A function was added to check if a role had the specific permissions (action, scope, entity) defined.
Why it was changed: This checking function provides a base for further functionality with each permission. For example, the function could be called when a user attempts to perform a specific action to check if they are permitted.
How was it changed: A new file checkPermissions.mjs was created, containing the hasPermission function. This function takes in a role, action, scope, and entity and loops through permissions constant previously defined to check for a match. A test case was also added in __test__.mjs. (The code is not fully functional quite yet but we are almost there!)

2024-10-14 22:35 UTC, sarah-fidahussain-SLU requested changes
Overall, the code is concise so good work. I think the for loops need some clarifying as to what they are doing, and the __test__.mjs file is still in progress but looks like most of the elements are there.

2024-10-14 22:35 UTC, sarah-fidahussain-SLU commented on components/classroom/groups/checkPermissions.mjs
> +    for(let i=0; i<rolePermissions.length; i++){ //building a two-dimensional array (i is number of permissions, j is action-scope-entity)
To clarify, is the reason why you are using the number of permissions is so you can iterate through the permissions the right number of times?

2024-10-14 22:35 UTC, sarah-fidahussain-SLU commented on components/classroom/groups/checkPermissions.mjs
> +    for(let i=0; i<rolePermissions.length;i++){//now traversing that array
what exactly is occurring when you traverse the array? are permissions being attached to them?

2024-10-15 23:50 UTC, MutyaSowmya123 requested changes
For this issue to write hasPermissions function, the expectation is to just implement the if conditions for the requirements specified in the issue. The for loops implementation is not really required.

2024-10-21 03:51 UTC, camilledaugherty commented
changes have been submitted! unfortunately after a lot of trial and error i was not able to get the if conditions in the description to work, so i went back to my original implementation which is now functional.

2024-10-22 03:49 UTC, MutyaSowmya123 approved these changes

2024-10-22 03:49 UTC, merged