Landing page
oss-slu/TPEN-interfaces pull request #20
Opened 2024-10-14 20:19 UTC by Matthew-Clendenning

Fixes #17 

What was changed: Fixed an error where the landing page wasn't styled correctly. Created a file to handle user input where the user inputs a project ID and displays the project details on another page.

Why it was changed: These changes are needed because specific users need to be able to view the details of a project they want to manipulate.

How it was changed: Created a JavaScript file where it fetches the project data from the API if the project exists. If it does exist it displays the data on another html page, otherwise it will give an error on the page. The functionality isn't quite sound and receives a 500 internal server error.

2024-10-16 00:27 UTC, MutyaSowmya123 requested changes
- remove menutoggle.js we don't need that at present.

- Also revert the changes done in test.html file.

Everything else seems good, work on these changes for now, I waiting for some feedback from our client. So based on that I may add some more changes further.

2024-10-16 21:12 UTC, kate-holdener commented on components/classroom/fetchData.mjs
> +    const token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwczovL3N0b3J
Generally, it's not a good idea to have tokens in a GitHub repository. @Matthew-Clendenning @MutyaSowmya123 was this an intentional change?

2024-10-16 21:13 UTC, kate-holdener commented on components/classroom/groups/api/fetchProjectData.mjs
> +const bearerToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwczovL3N0b
Generally, it's not a good idea to have tokens in a GitHub repository. @Matthew-Clendenning @MutyaSowmya123 was this an intentional change?

2024-10-16 21:13 UTC, kate-holdener commented on components/classroom/main.js
> +    const bearerToken = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwczovL
Generally, it's not a good idea to have tokens in a GitHub repository. @Matthew-Clendenning @MutyaSowmya123 was this an intentional change?

2024-10-16 21:15 UTC, kate-holdener commented on components/classroom/groups/api/UpdateProjectData.mjs
You deleted this file? intentionally or not?

2024-10-16 21:15 UTC, kate-holdener commented on components/classroom/groups/utils/authHelper.mjs
This file was deleted, it seems like an accidental change.

2024-10-16 21:16 UTC, kate-holdener commented on components/classroom/server.js
This file was deleted, seems like an accidental change.

2024-10-16 21:16 UTC, kate-holdener commented on components/classroom/package-lock.json
You probably didn't mean to delete this file.

2024-10-16 21:17 UTC, kate-holdener commented
@Matthew-Clendenning @MutyaSowmya123 Several files were deleted with this PR. It seems like an accidental change, which is concerning. Could you clarify?

2024-10-19 05:36 UTC, MutyaSowmya123 commented
> @Matthew-Clendenning @MutyaSowmya123 Several files were deleted with this PR. It seems like an accidental change, which is concerning. Could you clarify?
We were transitioning from working on MongoDB to the TPEN services API, which required significant restructuring of our codebase. The files deleted were part of that process and were deemed unnecessary for the new implementation. We believe this will ultimately improve the functionality and maintainability of our code.

2024-10-21 15:52 UTC, MutyaSowmya123 approved these changes

2024-10-21 16:25 UTC, camilledaugherty approved these changes

2024-10-21 22:01 UTC, merged