altered getProjects to parse and return contributors
oss-slu/TPEN-interfaces pull request #41
Opened 2024-11-25 06:50 UTC by sarah-fidahussain-SLU

Fixes #38 

What was changed: Altered the functionality of fetching projects to also fetch contributors and attach it to the projects object. This is done by fetching the contributors through the API. The rendering is also updated to account for displaying contributors.
Why was it changed: The previous getProjects function did not account for displaying contributor data for a project.
How was it changed: 
-  in the index.mjs: 
- render(): updated render function to include contributor formatting
- getProjects(): attaches contributor data to projects object
- fetchContributors(): assists getProjects() by handling the fetch contributor logic
- managePermissions: this is not fully implemented as there are issues with getting projectData to show up at all because of log-in issues. for now, it displays an alert with the contributor ID because login issues are preventing project data from loading properly.

2024-11-26 05:25 UTC, MutyaSowmya123 requested changes
Check the branch is up to date with the main, as the functionality working in the main seems missing in this branch.

2024-11-26 05:27 UTC, sarah-fidahussain-SLU commented
I just pulled changes on main and it says that it is already up to date. what could be wrong?

2024-11-28 04:22 UTC, sarah-fidahussain-SLU commented
I just pushed some changes that make it so when you click on the project, only the contributor details are displayed.

2024-11-29 15:12 UTC, MutyaSowmya123 commented
![image](https://github.com/user-attachments/assets/d07d3561-9720-492b-b81b-74fe6d6ec935)
The projects associated with the user is not not being fetched and so the contributor details.

2024-11-30 23:04 UTC, sarah-fidahussain-SLU commented
<img width="1440" alt="Screenshot 2024-11-30 at 5 04 04 PM" src="https://github.com/user-attachments/assets/a729fe9b-a97a-42f6-a204-25b6f6c4022e">
This is what happens when I run index.html

2024-12-01 20:04 UTC, MutyaSowmya123 approved these changes

2024-12-01 20:04 UTC, merged