sprint 1 issue 5 resolved
oss-slu/TPEN-interfaces pull request #7
Opened 2024-09-16 01:55 UTC by camilledaugherty

This pull request resolves issue #5.

What was changed: A landing page for our classroom interface was created. This includes a header, footer, and vertical navigation menu to link to future pages.
Why it was changed: We needed a specific page for our interface, as using the default TPEN page would not fit our specifications. These changes will provide a base webpage for us to develop our site and make things simple for users.
How it was changed: I added a classroom folder inside components with two files: an html file with our landing page's code, and a css file with our page's styles.

2024-09-16 22:17 UTC, sarah-fidahussain-SLU requested changes
The header and the footer look correct when I ran the index.html file. However, I believe the vertical pane should be left-justified and not be below the header, rather to the left of the header and the footer. I included an image of what the vertical pane seems to look like based on a web search.

![image](https://github.com/user-attachments/assets/58a5cec9-ff6b-4055-b4f0-c5b95212a217)

2024-09-16 22:27 UTC, sarah-fidahussain-SLU requested changes
Once I added a link to the html that links the css file, this is the result I am getting: 
<img width="1440" alt="Screenshot 2024-09-16 at 5 24 58 PM" src="https://github.com/user-attachments/assets/401fd3ad-d762-43d4-9785-6ed0cbe4e876">

Looks good to me now, but I think the gray box is not overlaying the home tab fully.

2024-09-18 14:38 UTC, kate-holdener commented
> This pull request resolves issue #5.
> 
> What was changed: A landing page for our classroom interface was created. This includes a header, footer, and vertical navigation menu to link to future pages. Why it was changed: We needed a specific page for our interface, as using the default TPEN page would not fit our specifications. These changes will provide a base webpage for us to develop our site and make things simple for users. How it was changed: I added a classroom folder inside components with two files: an html file with our landing page's code, and a css file with our page's styles. Layout pictured below: ![image](https://private-user-images.githubusercontent.com/95842392/367982268-d432012c-7df4-4c74-92cc-b474b2081c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzA1NjIsIm5iZiI6MTcyNjY3MDI2MiwicGF0aCI6Ii85NTg0MjM5Mi8zNjc5ODIyNjgtZDQzMjAxMmMtN2RmNC00Yzc0LTkyY2MtYjQ3NGIyMDgxYzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE0Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTMxYjlkN2RmMjFmN2VjYjA3MmJlYmRkOGE2ZDk4MWFhMmFiMTgwN2U5NzdkMGFjMWNlNDM0ZDUzZWU3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJT7qbEOTdXBKBbZ0QFJSKwVYrg2atmKthMnFHBAowI)

Please use:
Fixes #5 
This will automatically close the issue, when this pull request is merged.

2024-09-18 14:43 UTC, kate-holdener commented on _site/default-transcribe/index.html
@camilledaugherty I see that you deleted three files from the _site/default_transcribe directory. Looking at the main branch of your repo, I don't see a _site/default_transcribe directory. From which branch did you create your branch?

2024-09-18 16:28 UTC, MutyaSowmya123 requested changes
->Link the styles.css in the HTML page
->Check the styles that apply correctly to the elements
   
I noticed that the files in the _site folder were deleted. Just a reminder that while these files are typically generated and not tracked in version control, it’s important to ensure that the original source files are preserved.

2024-09-18 23:23 UTC, camilledaugherty commented on _site/default-transcribe/index.html
@kate-holdener I just created it from the main branch. I'm not quite sure what those files are and I don't remember making any changes, please let me know if that is a problem!

2024-09-19 00:27 UTC, MutyaSowmya123 commented on _site/default-transcribe/index.html
@camilledaugherty The `_site` directory typically contains generated files from a static site generator. It often includes HTML, CSS, and JavaScript files that are built from your source content. I think deleting these files doesn't create a problem for now. But in future ensure the original source files are preserved.

2024-09-23 00:22 UTC, camilledaugherty commented
requested changes have been made :)

2024-09-23 06:44 UTC, sarah-fidahussain-SLU approved these changes

2024-09-23 15:24 UTC, MutyaSowmya123 approved these changes

2024-09-23 22:43 UTC, merged