Sprint 1 issue #6 Resolved
oss-slu/TPEN-interfaces pull request #8
Opened 2024-09-16 04:29 UTC by Matthew-Clendenning

What was changed: Wrote documentation about what TPEN, TPEN API, and TPEN data services are. I also made changes to the styling on landing page.

Why was it changed: Added documentation so users can have a clear understanding of what TPEN is and how to use it. Style changes to the landing page was necessary for mobile users to access the website easily.

How was it changed: I created a README.md file with the information about TPEN. Edited the index.html file and added a hamburger menu for mobile users to access different pages of the site, username and password input boxes, and a submit button. Added media queries to the css file to make the site responsive. Created a small JavaScript file for the hamburger menu as well as logic for the username and password for testing purposes.

2024-09-16 22:16 UTC, camilledaugherty commented on components/classroom/README.md
> +* TPEN interface suuports many files e.g. `*js`, `*.css`, `*.html`, etc.,
supports is misspelled

2024-09-16 22:17 UTC, camilledaugherty commented on components/classroom/index.html
> +            -->
you can remove my comment! i didn't realize you were going to do the collapsible menu

2024-09-16 22:23 UTC, camilledaugherty commented on components/classroom/index.html
> +                    <h2>Sign Up/In</h2>
do we want to have two separate forms for signing up and logging in? if this works that's fine, just wondering bc signup might need more information from the user e.g. email address

2024-09-16 22:27 UTC, camilledaugherty commented on components/classroom/styles.css
> +    top: 20px;
super nitpicky but would look better if it was aligned with the website header! so top 30px instead of 20px

2024-09-18 14:44 UTC, kate-holdener commented
> This pull request resolves issue #6
> 
> What was changed: Wrote documentation about what TPEN, TPEN API, and TPEN data services are. I also made changes to the styling on landing page.
> 
> Why was it changed: Added documentation so users can have a clear understanding of what TPEN is and how to use it. Style changes to the landing page was necessary for mobile users to access the website easily.
> 
> How was it changed: I created a README.md file with the information about TPEN. Edited the index.html file and added a hamburger menu for mobile users to access different pages of the site, username and password input boxes, and a submit button. Added media queries to the css file to make the site responsive. Created a small JavaScript file for the hamburger menu as well as logic for the username and password for testing purposes.

Please use:
Fixes #6 
to automatically close the issue when the PR is merged.

2024-09-18 14:50 UTC, kate-holdener commented
@Matthew-Clendenning I see that you have the commit from @camilledaugherty in your branch. I'm confused on how it got here.

2024-09-18 15:26 UTC, Matthew-Clendenning commented
Hi Dr. Holdener,

I messaged our tech-lead Sowmya prior to sprint 1 because I was confused on how to edit the styling of our landing page that Camille made. She replied saying I needed to wait for her to finish her work and fetch the changes she made within her branch. I used git fetch to do so. I hope this didn't cause any issues.

Thank you,
Matthew Clendenning
________________________________
From: Kate Holdener ***@***.***>
Sent: Wednesday, September 18, 2024 9:50:36 AM
To: oss-slu/TPEN-interfaces ***@***.***>
Cc: Matthew Clendenning ***@***.***>; Mention ***@***.***>
Subject: Re: [oss-slu/TPEN-interfaces] Sprint 1 issue #6 Resolved (PR #8)


@Matthew-Clendenning<https://github.com/Matthew-Clendenning> I see that you have the commit from @camilledaugherty<https://github.com/camilledaugherty> in your branch. I'm confused on how it got here.

—
Reply to this email directly, view it on GitHub<https://github.com/oss-slu/TPEN-interfaces/pull/8#issuecomment-2358688977>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5YPU6PFUG66YEMHEGKMBO3ZXGHLZAVCNFSM6AAAAABOIPYQIGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJYGY4DQOJXG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-18 17:37 UTC, MutyaSowmya123 requested changes
Sign Up/In is not required just remove that:
`<h2>Sign Up/In</h2>`

2024-09-22 19:02 UTC, Matthew-Clendenning commented
Reviewed comments made by team and made the required changes.

2024-09-23 22:44 UTC, MutyaSowmya123 approved these changes

2024-09-23 22:45 UTC, merged