Sprint 1 Issue #1 Solved
oss-slu/TPEN-interfaces pull request #9
Opened 2024-09-16 20:36 UTC by sarah-fidahussain-SLU

Fixes issue [#1](https://github.com/CenterForDigitalHumanities/TPEN-interfaces/issues/1)
What was changed: A function for parsing the project ID from the URL was created. This includes both query string and hash. An HTML file was created to build a structure for the javascript code.
Why it was changed: There was no existing implementation for extraction of project ID.
How it was changed: I added a classroom folder inside components with two files: an index.html file which outputs project ID if it exists and states if it does not, and a project.js file which contains the function for parsing.

2024-09-16 22:27 UTC, Matthew-Clendenning requested changes

2024-09-16 22:27 UTC, Matthew-Clendenning commented on components/classroom/index.html
> +    <script>
Move this script tag into the 'project.js' file since you already have a js file created. It isn't a big deal but makes the html file cleaner.

2024-09-16 22:27 UTC, Matthew-Clendenning commented on components/classroom/project.js
> +function getProjectIDFromURL() {
Function is readable and clean. Maybe include a few comments describing what some functions do. For example, 'window.location.search', 'URLSearchParams', etc.

2024-09-16 22:27 UTC, Matthew-Clendenning commented on components/classroom/index.html
> +<!DOCTYPE html>
Remove the extra whitespaces to keep the code readable.

2024-09-18 14:53 UTC, kate-holdener commented
> Fixes issue [#1](https://github.com/CenterForDigitalHumanities/TPEN-interfaces/issues/1) What was changed: A function for parsing the project ID from the URL was created. This includes both query string and hash. An HTML file was created to build a structure for the javascript code. Why it was changed: There was no existing implementation for extraction of project ID. How it was changed: I added a classroom folder inside components with two files: an index.html file which outputs project ID if it exists and states if it does not, and a project.js file which contains the function for parsing.

Please use 
Fixes #1 
to automatically close the issue when this PR is merged.

2024-09-18 16:37 UTC, MutyaSowmya123 requested changes
Everything looks good. I just want to make one change: rename the `index.html` file to `test.html`. This will help ensure there are no merge conflicts with the landing page branch, which also contains `index.html`.

2024-09-23 15:30 UTC, Matthew-Clendenning approved these changes

2024-09-23 22:46 UTC, MutyaSowmya123 approved these changes

2024-09-23 22:46 UTC, merged